object DOMIds {
  val App = "app"
  val Banner = "banner"
  val Decklist = "decklist"
  val SearchBtn = "search-btn"
  val CartBtn = "cart-btn"
  val Status = "status"
  val Errors = "errors"
  val Results = "results"
  val MissingBox = "missing-box"
  val MissingList = "missing-list"
  val ExcludeLands = "exclude-lands"
  val CardCount = ".card-count"
  val DataEntryName = "data-entry-name"
}
